version: '3'
services:
  redis: 
    image: 'redis'
    expose:
      - 6379
  node-app:
    build: ./api
    depends_on:
      - redis
    ports:
      - "8000:8000"
  react-app:
    build: ./client
    ports:
      - "3000:3000"